@REM python visatt1.py --arch swin_tiny --image_path E:/selfsup/datasets/APTOS/val/0/00cc2b75cddd.png --output_dir vis/APTOS --pretrained_weights output_APTOS/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0

@REM @REM run visatt2 to extract feature of last layer
@REM python -m torch.distributed.launch --nproc_per_node=2 visatt2.py --data_path E:/selfsup/datasets/APTOS --output_dir vis/output_APTOS --pretrained_weights output_APTOS/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 5 --num_workers 1 MODEL.NUM_CLASSES 0
@REM python -m torch.distributed.launch --nproc_per_node=2 visatt2.py --data_path E:/selfsup/datasets/LAG --output_dir vis/output_LAG --pretrained_weights output_LAG/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 2 --num_workers 1 MODEL.NUM_CLASSES 0
@REM python -m torch.distributed.launch --nproc_per_node=2 visatt2.py --data_path E:/selfsup/datasets/AMD --output_dir vis/output_AMD --pretrained_weights output_AMD/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 2 --num_workers 1 MODEL.NUM_CLASSES 0

@REM @REM run vistsne to extract feature for tsne
@REM python -m torch.distributed.launch --nproc_per_node=2 vistsne.py --data_path E:/selfsup/datasets/APTOS --output_dir vis --pretrained_weights output_APTOS/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 5 --num_workers 1 MODEL.NUM_CLASSES 0
@REM python -m torch.distributed.launch --nproc_per_node=2 vistsne.py --data_path E:/selfsup/datasets/LAG --output_dir vis --pretrained_weights output_LAG/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 2 --num_workers 1 MODEL.NUM_CLASSES 0
@REM python -m torch.distributed.launch --nproc_per_node=2 vistsne.py --data_path E:/selfsup/datasets/AMD --output_dir vis --pretrained_weights output_AMD/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 2 --num_workers 1 MODEL.NUM_CLASSES 0




@REM @REM nfg att CAM vis
@REM python -m torch.distributed.launch --nproc_per_node=2 vis_CAM.py --data_path E:/FineGrained/datasets/CUB_200_2011 --output_dir vis --pretrained_weights output_CUB0.1/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 200 --num_workers 1 MODEL.NUM_CLASSES 0
@REM python -m torch.distributed.launch --nproc_per_node=2 vis_CAM.py --data_path E:/FineGrained/datasets/StanfordCars --output_dir vis --pretrained_weights output_Cars0.1/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 196 --num_workers 1 MODEL.NUM_CLASSES 0
@REM python -m torch.distributed.launch --nproc_per_node=2 vis_CAM.py --data_path E:/FineGrained/datasets/FGVC-Aircrafts --output_dir vis --pretrained_weights output_Aircrafts0.1/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 100 --num_workers 1 MODEL.NUM_CLASSES 0

@REM @REM nfg tsne vis
@REM python -m torch.distributed.launch --nproc_per_node=2 vistsne_0513.py --data_path E:/FineGrained/datasets/CUB_200_2011 --output_dir vis --pretrained_weights output_CUB0.1/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 200 --num_workers 1 MODEL.NUM_CLASSES 0
@REM python -m torch.distributed.launch --nproc_per_node=2 vistsne_0513.py --data_path E:/FineGrained/datasets/StanfordCars --output_dir vis --pretrained_weights output_Cars0.1/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 196 --num_workers 1 MODEL.NUM_CLASSES 0
@REM python -m torch.distributed.launch --nproc_per_node=2 vistsne_0513.py --data_path E:/FineGrained/datasets/FGVC-Aircrafts --output_dir vis --pretrained_weights output_Aircrafts0.1/checkpoint0270.pth --checkpoint_key teacher --batch_size_per_gpu 8 --arch swin_tiny --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --n_last_blocks 4 --num_labels 100 --num_workers 1 MODEL.NUM_CLASSES 0

@REM @REM nfg patch vis
@REM python -m torch.distributed.launch --nproc_per_node=2 vis_patch.py --arch swin_tiny --data_path E:/FineGrained/datasets/CUB_200_2011/train --output_dir output_CUB --batch_size_per_gpu 4 --epochs 300 --saveckp_freq 30 --teacher_temp 0.07 --warmup_epochs 10 --warmup_teacher_temp_epochs 30 --norm_last_layer false --use_dense_prediction True --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --pretrained_weights_ckpt output_CUB0.1/checkpoint0270.pth --start_epoch 270
@REM python -m torch.distributed.launch --nproc_per_node=2 vis_patch.py --arch swin_tiny --data_path E:/FineGrained/datasets/StanfordCars/train --output_dir output_Cars --batch_size_per_gpu 4 --epochs 300 --saveckp_freq 30 --teacher_temp 0.07 --warmup_epochs 10 --warmup_teacher_temp_epochs 30 --norm_last_layer false --use_dense_prediction False --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --pretrained_weights_ckpt output_Cars0.1/checkpoint0270.pth --start_epoch 270
@REM python -m torch.distributed.launch --nproc_per_node=2 vis_patch.py --arch swin_tiny --data_path E:/FineGrained/datasets/FGVC-Aircrafts/train --output_dir output_Aircrafts --batch_size_per_gpu 4 --epochs 300 --saveckp_freq 30 --teacher_temp 0.07 --warmup_epochs 10 --warmup_teacher_temp_epochs 30 --norm_last_layer false --use_dense_prediction True --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --pretrained_weights_ckpt output_Aircrafts0.1/checkpoint0270.pth --start_epoch 270

@REM nfg patch act
python analyze_models.py --arch swin_tiny --image_path vis/patch/CUB/0_view.png --output_dir vis/patch/act/CUB --pretrained_weights output_CUB0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/CUB/1_view.png --output_dir vis/patch/act/CUB --pretrained_weights output_CUB0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/CUB/2_view.png --output_dir vis/patch/act/CUB --pretrained_weights output_CUB0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/CUB/3_view.png --output_dir vis/patch/act/CUB --pretrained_weights output_CUB0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/CUB/4_view.png --output_dir vis/patch/act/CUB --pretrained_weights output_CUB0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/CUB/5_view.png --output_dir vis/patch/act/CUB --pretrained_weights output_CUB0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/CUB/6_view.png --output_dir vis/patch/act/CUB --pretrained_weights output_CUB0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/CUB/7_view.png --output_dir vis/patch/act/CUB --pretrained_weights output_CUB0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/CUB/8_view.png --output_dir vis/patch/act/CUB --pretrained_weights output_CUB0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/CUB/9_view.png --output_dir vis/patch/act/CUB --pretrained_weights output_CUB0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0

python analyze_models.py --arch swin_tiny --image_path vis/patch/Cars/0_view.png --output_dir vis/patch/act/Cars --pretrained_weights output_Cars0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Cars/1_view.png --output_dir vis/patch/act/Cars --pretrained_weights output_Cars0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Cars/2_view.png --output_dir vis/patch/act/Cars --pretrained_weights output_Cars0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Cars/3_view.png --output_dir vis/patch/act/Cars --pretrained_weights output_Cars0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Cars/4_view.png --output_dir vis/patch/act/Cars --pretrained_weights output_Cars0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Cars/5_view.png --output_dir vis/patch/act/Cars --pretrained_weights output_Cars0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Cars/6_view.png --output_dir vis/patch/act/Cars --pretrained_weights output_Cars0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Cars/7_view.png --output_dir vis/patch/act/Cars --pretrained_weights output_Cars0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Cars/8_view.png --output_dir vis/patch/act/Cars --pretrained_weights output_Cars0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Cars/9_view.png --output_dir vis/patch/act/Cars --pretrained_weights output_Cars0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0

python analyze_models.py --arch swin_tiny --image_path vis/patch/Airs/0_view.png --output_dir vis/patch/act/Airs --pretrained_weights output_Airs0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Airs/1_view.png --output_dir vis/patch/act/Airs --pretrained_weights output_Airs0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Airs/2_view.png --output_dir vis/patch/act/Airs --pretrained_weights output_Airs0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Airs/3_view.png --output_dir vis/patch/act/Airs --pretrained_weights output_Airs0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Airs/4_view.png --output_dir vis/patch/act/Airs --pretrained_weights output_Airs0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Airs/5_view.png --output_dir vis/patch/act/Airs --pretrained_weights output_Airs0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Airs/6_view.png --output_dir vis/patch/act/Airs --pretrained_weights output_Airs0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Airs/7_view.png --output_dir vis/patch/act/Airs --pretrained_weights output_Airs0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Airs/8_view.png --output_dir vis/patch/act/Airs --pretrained_weights output_Airs0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0
python analyze_models.py --arch swin_tiny --image_path vis/patch/Airs/9_view.png --output_dir vis/patch/act/Airs --pretrained_weights output_Airs0.1/checkpoint0270.pth --learning ssl --seed 8 --cfg experiments/imagenet/swin/swin_tiny_patch4_window14_224.yaml --vis_attention True --vis_correspondence False --measure_correspondence False MODEL.NUM_CLASSES 0